### ISSUE TITLE
No data display

### ISSUE THREAD

**Issue by fuqiang03** [tano-systems/luci-app-netports#3]
![QQ截图20191213230252](https://user-images.githubusercontent.com/26851715/70809751-68c69e80-1dfd-11ea-8642-e4f8d3f09de8.png)

openwrt master
Luabitop is already installed
Use full profile

config global 'global'
	option default_additional_info 'true'
	option default_h_mode 'false'
	option hv_mode_switch_button 'false'

config port
	option ifname 'ifb0'
	option disable '1'

config port
	option ifname 'ifb1'
	option disable '1'

config port
	option name 'Port 1'
	option ifname 'eth0'
	option type 'copper'

config port
	option name 'Port 2'
	option ifname 'eth1'
	option type 'copper'

config port
	option name 'Port 3'
	option ifname 'eth2'
	option type 'copper'

config port
	option name 'Port 4'
	option ifname 'eth3'
	option type 'copper'

config port 'hotplug_ip6tnl0'
	option name 'ip6tnl0'
	option ifname 'ip6tnl0'
	option type 'auto'

config port 'hotplug_gre0'
	option name 'gre0'
	option ifname 'gre0'
	option type 'auto'

config port 'hotplug_gretap0'
	option name 'gretap0'
	option ifname 'gretap0'
	option type 'auto'

config port 'hotplug_erspan0'
	option name 'erspan0'
	option ifname 'erspan0'
	option type 'auto'

config port 'hotplug_bond0'
	option name 'bond0'
	option ifname 'bond0'
	option type 'auto'

config port 'hotplug_teql0'
	option name 'teql0'
	option ifname 'teql0'
	option type 'auto'

config port 'hotplug_imq0'
	option name 'imq0'
	option ifname 'imq0'
	option type 'auto'

config port 'hotplug_imq1'
	option name 'imq1'
	option ifname 'imq1'
	option type 'auto'

**Comment by namedun** [comment]
Please show the output of this command:
```
echo '{}' | /usr/libexec/rpcd/netports call getPortsInfo
```

**Comment by fuqiang03** [comment]
root@OpenWrt:/# echo '{}' | /usr/libexec/rpcd/netports call getPortsInfo
{"data":[{"operstate":"up","ifname":"eth0","id":"cfg04614a","bridge":{"ifname":"br-lan","port":1},"stats":{"rx_bytes":423862,"tx_packets":3290,"tx_bytes":2920299,"rx_packets":2196},"hwaddr":"40:62:31:0a:83:8c","ntm_bridge":{"fwzone":"lan","netname":"lan","fwzone_color":"#90f090","fwzone_sid":"cfg02dc81"},"name":"Port 1","speed":1000,"carrier":1,"adminstate":"up","type":"copper","duplex":"full"},{"operstate":"down","ifname":"ip6tnl0","id":"hotplug_ip6tnl0","hwaddr":"00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00","name":"ip6tnl0","carrier":0,"adminstate":"down","type":"copper","stats":{"rx_bytes":0,"tx_packets":0,"tx_bytes":0,"rx_packets":0}},{"operstate":"down","ifname":"gre0","id":"hotplug_gre0","hwaddr":"00:00:00:00","name":"gre0","carrier":0,"adminstate":"down","type":"copper","stats":{"rx_bytes":0,"tx_packets":0,"tx_bytes":0,"rx_packets":0}},{"operstate":"down","ifname":"gretap0","id":"hotplug_gretap0","hwaddr":"00:00:00:00:00:00","name":"gretap0","carrier":0,"adminstate":"down","type":"copper","stats":{"rx_bytes":0,"tx_packets":0,"tx_bytes":0,"rx_packets":0}},{"operstate":"down","ifname":"erspan0","id":"hotplug_erspan0","hwaddr":"00:00:00:00:00:00","name":"erspan0","carrier":0,"adminstate":"down","type":"copper","stats":{"rx_bytes":0,"tx_packets":0,"tx_bytes":0,"rx_packets":0}},{"operstate":"down","ifname":"bond0","id":"hotplug_bond0","hwaddr":"92:94:61:55:a6:e4","name":"bond0","carrier":0,"adminstate":"down","type":"copper","stats":{"rx_bytes":0,"tx_packets":0,"tx_bytes":0,"rx_packets":0}},{"operstate":"down","ifname":"teql0","id":"hotplug_teql0","hwaddr":"","name":"teql0","carrier":0,"adminstate":"down","type":"copper","stats":{"rx_bytes":0,"tx_packets":0,"tx_bytes":0,"rx_packets":0}},{"operstate":"down","ifname":"imq0","id":"hotplug_imq0","hwaddr":"","name":"imq0","carrier":0,"adminstate":"down","type":"copper","stats":{"rx_bytes":0,"tx_packets":0,"tx_bytes":0,"rx_packets":0}},{"operstate":"down","ifname":"imq1","id":"hotplug_imq1","hwaddr":"","name":"imq1","carrier":0,"adminstate":"down","type":"copper","stats":{"rx_bytes":0,"tx_packets":0,"tx_bytes":0,"rx_packets":0}}],"count":9}
root@OpenWrt:/#

**Comment by namedun** [comment]
Provided output is good and should work correctly. Everything is displayed correctly when checking on the latest openwrt master with your data and config:

![image](https://user-images.githubusercontent.com/13316680/70814672-01005b80-1ddd-11ea-8c96-a9b5d0c2bc9e.png)

![image](https://user-images.githubusercontent.com/13316680/70814289-39ec0080-1ddc-11ea-8f75-2b15a5758920.png)

Maybe you need to restart rpcd service by command `/etc/init.d/rpcd restart`.

Please reopen this issue if you have any furher questions.

**Comment by fuqiang03** [comment]
thank you

**Comment by fuqiang03** [comment]
It's really beautiful
It would be great if "openwrt" were all like this
