### ISSUE TITLE
not sure if "luasrc" folder should exist

### ISSUE THREAD

**Issue by ferboiar** [tano-systems/luci-app-netports#4]
Hi

should the `luasrc` folder exist? 

There is a `pscp` command trying to copy the folder but it isn't exist...:
```
IF EXIST %~dp0/luasrc (
 	pscp -r %EXTRA_OPTIONS% %~dp0/luasrc/* %HOST%:%LUCI_LUASRC_PATH%
)
```

**Comment by namedun** [comment]
This is an old deploy script that was written for an old version with a lua backend. The current version of the application is rewritten in JavaScript and has no luasrc directory. So, the no luasrc is normal.
